### PR TITLE
Fix the "do not copy existing values" checkbox

### PR DESCRIPTION
**Pull request by qzminski**
The checkbox had no effect on our website. I did not fully understand this "do not copy existing values" JavaScript logic, so please let me know if there's something I missed.

### CODE REVIEW

**Comment by fritzmg** [comment]
When you duplicate a fieldset, the current input values will be duplicated too. This setting is supposed to prevent that.

**Comment by qzminski** [comment]
Hmm, in my use case they were not duplicated at all… could you check if it works for you?

**Comment by fritzmg** [comment]
Yeah, it currently does not work. This condition

https://github.com/inspiredminds/contao-fieldset-duplication/blob/25e2c186758f0b71d7511e24a89aac2a68d87189/src/Resources/public/jquery.fieldset.duplication.js#L116

is currently always true.

**Comment by qzminski** [comment]
Exactly, because [this](https://github.com/inspiredminds/contao-fieldset-duplication/blob/25e2c186758f0b71d7511e24a89aac2a68d87189/src/Resources/public/jquery.fieldset.duplication.js#L113) is always an empty string. My PR should fix that.

**Comment by fritzmg** [comment]
Hm, I think the intention is to not copy user input, but still copy default values. I have fixed this in b587247 now.

**Pull request closed without merging**
